### ISSUE TITLE
Problem about using nvBWT to build index

### ISSUE THREAD

**Issue by guoguixin** [NVlabs/nvbio-gpl#2]
Hi, I’m Guixin Guo from BGI-Shenzhen and I work for Bingqiang Wang. I was trying to use the aligner nvBowtie and encountered the following problem when using nvBWT to build the index of the reference genome:
info    : max length : -1
info    : input      : "ref.fa"
info    : output     : "ref-index"
info    : directory  : ""
info    :
info    : counting bps... started
info    :   counting "ref.fa"
info    : counting bps... done
info    :
info    : stats:
info    :   reads           : 14
info    :   sequence length : 168717020 bps (40.2 MB)
info    :   buffer size     : 84.4 MB
info    :
info    : buffering bps... started
info    :   buffering "ref.fa"
info    : buffering bps... done
info    :   crc: 1388273006
info    :
info    : writing "ref-index.pac"... started
info    : writing "ref-index.pac"... done
info    :
info    : building forward BWT... started
verbose :   building DCS... started
verbose :   super-block-size: 160.9 M
verbose :   device-alloc(0.7 GB)... started
verbose :     free: 11.0 GB
verbose :   device-alloc(1.8 GB)... done
verbose :   bucket counting
verbose :     max bucket size: 0
verbose :       c-sort  : 0.0s
verbose :   collect buckets[0:1048576](0 suffixes)
verbose :   collect : 0.0s, 0.0 M suffixes/s
verbose :     setup   : 0.0s
verbose :     flatten : 0.0s
verbose :     b-sort  : 0.0s
verbose :     search  : 0.0s
verbose :     copy    : 0.0s
verbose :   sufsort buckets[0:1048576](0 suffixes, -nan M suffixes/s)
nvBWT: /lustre/home/bgizl/test/nvbio-master/contrib/moderngpu/src/mgpucontext.cu:454: virtual cudaError_t mgpu::CudaAllocBuckets::Malloc(size_t, void**): Assertion `SanityCheck()' failed.

The suffixes number in “verbose :   collect buckets[0:1048576](0 suffixes)” was strange, so I checked the code and found that priv::copy_if in function blockwise_build(nvbio/sufsort/blockwise_sufsort.h) didn’t work correctly: the sample_size is 0 after the for loop. I checked the content of dcs.d_bitmask, which I thought was correct, the content in it was {0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0}.

I tried different combinations of versions of GCC and CUDA to compile nvbio and run the code on two different GPUs respectively, but the program still failed in the same problem.

System:         Red Hat Enterprise Linux Server release 6.3 (Santiago)
GCC version:        4.4.3 and 4.8.2
CUDA version:   5.0, 5.5 and 6.0
GPU:            Tesla K20m and Tesla K40c

Is there anything I missed when I run the program? Any advice is appreciated!

**Comment by jpantaleoni** [comment]
I think the problem is I have inadvertendly pushed out the wrong version of CUB (contrib/cub).
We'are going to push out an update soon to fix this and a couple other issues (meanwhile you could try replacing it with the latest, from http://nvlabs.github.io/cub/)

**Comment by nsubtil** [comment]
guoguixin, did this problem get fixed for you?

**Comment by guoguixin** [comment]
Yes, the program can run well now. Thank you very much!
