### ISSUE TITLE
Please tag a stable release of NVBIO 0.9.5

### ISSUE THREAD

**Issue by sjackman** [NVlabs/nvbio-gpl#3]
Thanks!

**Comment by psteinb** [comment]
I second this issue. The nvbio website states version 0.9.5 and links to an associated tarball (which inturn just points to the github repo).

so, please do tag 0.9.5!

**Comment by nsubtil** [comment]
That's a good point, we haven't been tagging our releases so far.

We'll add a 0.9.5 tag later today and figure out how to handle this moving forward. Thanks for the heads up!

**Comment by nsubtil** [comment]
I've tagged 3e6efbdf as v0.9.5. We'll make sure to start tagging releases moving forward.

Closing.
