### ISSUE TITLE
nvidia_331_uvm error

### ISSUE THREAD

**Issue by peterdfields** [NVlabs/nvbio-gpl#7]
I'm getting the following error when running nvBWT:

modprobe: ERROR: ../libkmod/libkmod-module.c:809 kmod_module_insert_module() could not find module by name='nvidia_331_uvm'
modprobe: ERROR: could not insert 'nvidia_331_uvm': Function not implemented

and then at the end:

error   : caught a std::bad_alloc exception:
error   :   std::bad_alloc

NVIDIA driver: 334.21
CUDA: 6.01
Ubuntu 14.04

Let me know if additional info would be helpful.

**Comment by fogelton** [comment]
Did you solved this problem? could you give me a hand?

thanks

**Comment by CBouchard** [comment]
I had a similar issue when running a CUDA test sample.

modprobe: ERROR: ../libkmod/libkmod-module.c:809 kmod_module_insert_module() could not find module by name='nvidia_331_uvm'
modprobe: ERROR: could not insert 'nvidia_331_uvm': Function not implemented
cudaGetDeviceCount returned 30
-> unknown error
Result = FAIL

I solved the issue by installing the nvidia-331-uvm package.

sudo apt-get install nvidia-331-uvm
